
require 'page-object/elements/element'
require 'page-object/elements/link'
require 'page-object/elements/text_field'
require 'page-object/elements/select_list'
require 'page-object/elements/check_box'
require 'page-object/elements/button'
require 'page-object/elements/radio_button'
require 'page-object/elements/div'
require 'page-object/elements/table'
require 'page-object/elements/table_cell'
require 'page-object/elements/table_row'
require 'page-object/elements/span'
